"""Type stubs for alembic_rs - Alembic file format bindings for Python."""

from typing import List, Optional, Tuple, Iterator, Any

# =============================================================================
# Archives
# =============================================================================

class IArchive:
    """Read-only Alembic archive."""
    def __init__(self, path: str) -> None: ...
    def valid(self) -> bool: ...
    def getName(self) -> str: ...
    def getTop(self) -> IObject: ...
    def getAppName(self) -> str: ...
    def getDateWritten(self) -> str: ...
    def getUserDescription(self) -> str: ...
    def getDccFps(self) -> float: ...
    def getNumTimeSamplings(self) -> int: ...
    def getTimeSampling(self, index: int) -> Optional[TimeSampling]: ...
    def getMetadataKeys(self) -> List[str]: ...
    def getMetadata(self, key: str) -> Optional[str]: ...

class OArchive:
    """Write-only Alembic archive."""
    @staticmethod
    def create(path: str) -> OArchive: ...
    def setAppName(self, name: str) -> None: ...
    def setUserDescription(self, desc: str) -> None: ...
    def writeArchive(self, root: OObject) -> None: ...
    def __enter__(self) -> OArchive: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

# =============================================================================
# Objects
# =============================================================================

class IObject:
    """Read-only object in the hierarchy."""
    def getName(self) -> str: ...
    def getFullName(self) -> str: ...
    def getNumChildren(self) -> int: ...
    def getChild(self, index: int) -> IObject: ...
    def getChildByName(self, name: str) -> Optional[IObject]: ...
    def getSchemaType(self) -> str: ...
    def getNumSamples(self) -> int: ...
    def isPolyMesh(self) -> bool: ...
    def isXform(self) -> bool: ...
    def isSubD(self) -> bool: ...
    def isCurves(self) -> bool: ...
    def isPoints(self) -> bool: ...
    def isCamera(self) -> bool: ...
    def isLight(self) -> bool: ...
    def isNuPatch(self) -> bool: ...
    def isFaceSet(self) -> bool: ...
    def getPolyMeshSample(self, index: int = 0) -> PolyMeshSample: ...
    def getXformSample(self, index: int = 0) -> XformSample: ...
    def getSubDSample(self, index: int = 0) -> SubDSample: ...
    def getCurvesSample(self, index: int = 0) -> CurvesSample: ...
    def getPointsSample(self, index: int = 0) -> PointsSample: ...
    def getCameraSample(self, index: int = 0) -> CameraSample: ...
    def getLightSample(self, index: int = 0) -> LightSample: ...
    def getNuPatchSample(self, index: int = 0) -> NuPatchSample: ...
    def getFaceSetSample(self, index: int = 0) -> FaceSetSample: ...
    def getPositions(self, index: int = 0) -> List[List[float]]: ...
    def getFaceCounts(self, index: int = 0) -> List[int]: ...
    def getFaceIndices(self, index: int = 0) -> List[int]: ...
    def getMatrix(self, index: int = 0) -> List[List[float]]: ...
    def getProperties(self) -> ICompoundProperty: ...
    def getFaceSetNames(self) -> List[str]: ...
    def getFaceSet(self, name: str) -> IFaceSet: ...
    def __iter__(self) -> Iterator[IObject]: ...
    def __len__(self) -> int: ...

class OObject:
    """Write-only object container."""
    def __init__(self, name: str) -> None: ...
    def addPolyMesh(self, mesh: OPolyMesh) -> None: ...
    def addXform(self, xform: OXform) -> None: ...
    def addSubD(self, subd: OSubD) -> None: ...
    def addCurves(self, curves: OCurves) -> None: ...
    def addPoints(self, points: OPoints) -> None: ...
    def addCamera(self, camera: OCamera) -> None: ...
    def addLight(self, light: OLight) -> None: ...
    def addNuPatch(self, nupatch: ONuPatch) -> None: ...
    def addChild(self, child: OObject) -> None: ...
    def addMaterial(self, material: OMaterial) -> None: ...
    def addCollections(self, collections: OCollections) -> None: ...

# =============================================================================
# Schema Readers (Original Alembic API Style)
# =============================================================================

class IPolyMesh:
    """PolyMesh schema wrapper."""
    def __init__(self, obj: IObject) -> None: ...
    def getSchema(self) -> IPolyMeshSchema: ...
    def valid(self) -> bool: ...
    def getName(self) -> str: ...
    def getFullName(self) -> str: ...

class IPolyMeshSchema:
    """PolyMesh schema accessor."""
    def getNumSamples(self) -> int: ...
    def isConstant(self) -> bool: ...
    def getValue(self, index: int = 0) -> PolyMeshSample: ...
    def getTimeSamplingIndex(self) -> int: ...

class IXform:
    """Xform schema wrapper."""
    def __init__(self, obj: IObject) -> None: ...
    def getSchema(self) -> IXformSchema: ...
    def valid(self) -> bool: ...
    def getName(self) -> str: ...
    def getFullName(self) -> str: ...

class IXformSchema:
    """Xform schema accessor."""
    def getNumSamples(self) -> int: ...
    def isConstant(self) -> bool: ...
    def getValue(self, index: int = 0) -> XformSample: ...
    def getTimeSamplingIndex(self) -> int: ...
    def getInheritsXforms(self, index: int = 0) -> bool: ...

class ISubD:
    """SubD schema wrapper."""
    def __init__(self, obj: IObject) -> None: ...
    def getSchema(self) -> ISubDSchema: ...
    def valid(self) -> bool: ...
    def getName(self) -> str: ...
    def getFullName(self) -> str: ...

class ISubDSchema:
    """SubD schema accessor."""
    def getNumSamples(self) -> int: ...
    def isConstant(self) -> bool: ...
    def getValue(self, index: int = 0) -> SubDSample: ...
    def getTimeSamplingIndex(self) -> int: ...

class ICurves:
    """Curves schema wrapper."""
    def __init__(self, obj: IObject) -> None: ...
    def getSchema(self) -> ICurvesSchema: ...
    def valid(self) -> bool: ...
    def getName(self) -> str: ...
    def getFullName(self) -> str: ...

class ICurvesSchema:
    """Curves schema accessor."""
    def getNumSamples(self) -> int: ...
    def isConstant(self) -> bool: ...
    def getValue(self, index: int = 0) -> CurvesSample: ...
    def getTimeSamplingIndex(self) -> int: ...

class IPoints:
    """Points schema wrapper."""
    def __init__(self, obj: IObject) -> None: ...
    def getSchema(self) -> IPointsSchema: ...
    def valid(self) -> bool: ...
    def getName(self) -> str: ...
    def getFullName(self) -> str: ...

class IPointsSchema:
    """Points schema accessor."""
    def getNumSamples(self) -> int: ...
    def isConstant(self) -> bool: ...
    def getValue(self, index: int = 0) -> PointsSample: ...
    def getTimeSamplingIndex(self) -> int: ...

class ICamera:
    """Camera schema wrapper."""
    def __init__(self, obj: IObject) -> None: ...
    def getSchema(self) -> ICameraSchema: ...
    def valid(self) -> bool: ...
    def getName(self) -> str: ...
    def getFullName(self) -> str: ...

class ICameraSchema:
    """Camera schema accessor."""
    def getNumSamples(self) -> int: ...
    def isConstant(self) -> bool: ...
    def getValue(self, index: int = 0) -> CameraSample: ...
    def getTimeSamplingIndex(self) -> int: ...

class ILight:
    """Light schema wrapper."""
    def __init__(self, obj: IObject) -> None: ...
    def getSchema(self) -> ILightSchema: ...
    def valid(self) -> bool: ...
    def getName(self) -> str: ...
    def getFullName(self) -> str: ...

class ILightSchema:
    """Light schema accessor."""
    def getNumSamples(self) -> int: ...
    def isConstant(self) -> bool: ...
    def getValue(self, index: int = 0) -> LightSample: ...
    def getTimeSamplingIndex(self) -> int: ...

class INuPatch:
    """NuPatch schema wrapper."""
    def __init__(self, obj: IObject) -> None: ...
    def getSchema(self) -> INuPatchSchema: ...
    def valid(self) -> bool: ...
    def getName(self) -> str: ...
    def getFullName(self) -> str: ...

class INuPatchSchema:
    """NuPatch schema accessor."""
    def getNumSamples(self) -> int: ...
    def isConstant(self) -> bool: ...
    def getValue(self, index: int = 0) -> NuPatchSample: ...
    def getTimeSamplingIndex(self) -> int: ...

class IFaceSet:
    """FaceSet reader (direct access)."""
    def getName(self) -> str: ...
    def getFullName(self) -> str: ...
    def getNumSamples(self) -> int: ...
    def isConstant(self) -> bool: ...
    def getSample(self, index: int = 0) -> FaceSetSample: ...
    def getFaceExclusivity(self) -> str: ...

class IFaceSetTyped:
    """FaceSet schema wrapper (original API style)."""
    def __init__(self, obj: IObject) -> None: ...
    def getSchema(self) -> IFaceSetSchema: ...
    def valid(self) -> bool: ...
    def getName(self) -> str: ...
    def getFullName(self) -> str: ...

class IFaceSetSchema:
    """FaceSet schema accessor."""
    def getNumSamples(self) -> int: ...
    def isConstant(self) -> bool: ...
    def getValue(self, index: int = 0) -> FaceSetSample: ...
    def getTimeSamplingIndex(self) -> int: ...
    def getFaceExclusivity(self) -> str: ...

class IGeomParam:
    """Geometry parameter reader."""
    def getName(self) -> str: ...
    def getScope(self) -> str: ...
    def isIndexed(self) -> bool: ...
    def getNumSamples(self) -> int: ...
    def getSample(self, index: int = 0) -> GeomParamSample: ...

# =============================================================================
# Sample Types (Read)
# =============================================================================

class PolyMeshSample:
    """PolyMesh sample data."""
    @property
    def positions(self) -> List[List[float]]: ...
    @property
    def faceCounts(self) -> List[int]: ...
    @property
    def faceIndices(self) -> List[int]: ...
    @property
    def normals(self) -> Optional[List[List[float]]]: ...
    @property
    def uvs(self) -> Optional[List[List[float]]]: ...
    @property
    def velocities(self) -> Optional[List[List[float]]]: ...
    @property
    def selfBounds(self) -> Optional[Tuple[List[float], List[float]]]: ...

class XformSample:
    """Xform sample data."""
    @property
    def matrix(self) -> List[List[float]]: ...
    @property
    def inherits(self) -> bool: ...
    def getTranslation(self) -> List[float]: ...
    def getScale(self) -> List[float]: ...
    def getRotation(self) -> List[float]: ...
    def getRotationQuaternion(self) -> List[float]: ...

class SubDSample:
    """SubD sample data."""
    @property
    def positions(self) -> List[List[float]]: ...
    @property
    def faceCounts(self) -> List[int]: ...
    @property
    def faceIndices(self) -> List[int]: ...
    @property
    def scheme(self) -> str: ...
    @property
    def selfBounds(self) -> Optional[Tuple[List[float], List[float]]]: ...

class CurvesSample:
    """Curves sample data."""
    @property
    def positions(self) -> List[List[float]]: ...
    @property
    def numVertices(self) -> List[int]: ...
    @property
    def curveType(self) -> str: ...
    @property
    def basis(self) -> str: ...
    @property
    def wrap(self) -> str: ...
    @property
    def widths(self) -> Optional[List[float]]: ...
    @property
    def selfBounds(self) -> Optional[Tuple[List[float], List[float]]]: ...

class PointsSample:
    """Points sample data."""
    @property
    def positions(self) -> List[List[float]]: ...
    @property
    def ids(self) -> List[int]: ...
    @property
    def velocities(self) -> Optional[List[List[float]]]: ...
    @property
    def widths(self) -> Optional[List[float]]: ...
    @property
    def selfBounds(self) -> Optional[Tuple[List[float], List[float]]]: ...

class CameraSample:
    """Camera sample data."""
    @property
    def focalLength(self) -> float: ...
    @property
    def horizontalAperture(self) -> float: ...
    @property
    def verticalAperture(self) -> float: ...
    @property
    def horizontalFilmOffset(self) -> float: ...
    @property
    def verticalFilmOffset(self) -> float: ...
    @property
    def lensSqueezeRatio(self) -> float: ...
    @property
    def nearClippingPlane(self) -> float: ...
    @property
    def farClippingPlane(self) -> float: ...
    @property
    def fStop(self) -> float: ...
    @property
    def focusDistance(self) -> float: ...
    def getFovHorizontal(self) -> float: ...

class LightSample:
    """Light sample data."""
    @property
    def color(self) -> Optional[List[float]]: ...
    @property
    def intensity(self) -> Optional[float]: ...

class NuPatchSample:
    """NuPatch sample data."""
    @property
    def positions(self) -> List[List[float]]: ...
    @property
    def numU(self) -> int: ...
    @property
    def numV(self) -> int: ...
    @property
    def uOrder(self) -> int: ...
    @property
    def vOrder(self) -> int: ...
    @property
    def uKnots(self) -> List[float]: ...
    @property
    def vKnots(self) -> List[float]: ...
    @property
    def selfBounds(self) -> Optional[Tuple[List[float], List[float]]]: ...

class FaceSetSample:
    """FaceSet sample data."""
    @property
    def faces(self) -> List[int]: ...
    @property
    def selfBounds(self) -> Optional[Tuple[List[float], List[float]]]: ...

class GeomParamSample:
    """GeomParam sample data."""
    @property
    def values(self) -> List[float]: ...
    @property
    def indices(self) -> Optional[List[int]]: ...
    @property
    def scope(self) -> str: ...
    @property
    def isIndexed(self) -> bool: ...

# =============================================================================
# Schema Writers
# =============================================================================

class OPolyMesh:
    """Write PolyMesh geometry."""
    def __init__(self, name: str) -> None: ...
    def addSample(self, positions: List[List[float]], face_counts: List[int], face_indices: List[int]) -> None: ...
    def setNormals(self, normals: List[List[float]], indices: Optional[List[int]] = None) -> None: ...
    def setUVs(self, uvs: List[List[float]], indices: Optional[List[int]] = None) -> None: ...
    def setVelocities(self, velocities: List[List[float]]) -> None: ...
    def addFaceSet(self, faceset: OFaceSet) -> None: ...

class OXform:
    """Write transform."""
    def __init__(self, name: str) -> None: ...
    def addMatrixSample(self, matrix: List[List[float]]) -> None: ...
    def addTranslationSample(self, x: float, y: float, z: float) -> None: ...
    def addRotationSample(self, x: float, y: float, z: float) -> None: ...
    def addScaleSample(self, x: float, y: float, z: float) -> None: ...

class OSubD:
    """Write subdivision surface."""
    def __init__(self, name: str) -> None: ...
    def addSample(self, positions: List[List[float]], face_counts: List[int], face_indices: List[int]) -> None: ...
    def setScheme(self, scheme: str) -> None: ...

class OCurves:
    """Write curves."""
    def __init__(self, name: str) -> None: ...
    def addSample(self, positions: List[List[float]], num_vertices: List[int]) -> None: ...
    def setCurveType(self, curve_type: str) -> None: ...
    def setBasis(self, basis: str) -> None: ...
    def setWrap(self, wrap: str) -> None: ...
    def setWidths(self, widths: List[float]) -> None: ...

class OPoints:
    """Write point cloud."""
    def __init__(self, name: str) -> None: ...
    def addSample(self, positions: List[List[float]], ids: List[int]) -> None: ...
    def setVelocities(self, velocities: List[List[float]]) -> None: ...
    def setWidths(self, widths: List[float]) -> None: ...

class OCamera:
    """Write camera."""
    def __init__(self, name: str) -> None: ...
    def addSample(self, focal_length: float = 35.0, h_aperture: float = 3.6, v_aperture: float = 2.4) -> None: ...
    def setClipping(self, near: float, far: float) -> None: ...
    def setFStop(self, fstop: float) -> None: ...
    def setFocusDistance(self, distance: float) -> None: ...

class OLight:
    """Write light."""
    def __init__(self, name: str) -> None: ...
    def addSample(self) -> None: ...

class ONuPatch:
    """Write NURBS patch."""
    def __init__(self, name: str) -> None: ...
    def addSample(self, positions: List[List[float]], num_u: int, num_v: int, u_order: int, v_order: int, u_knots: List[float], v_knots: List[float]) -> None: ...

class OFaceSet:
    """Write face set."""
    def __init__(self, name: str) -> None: ...
    def setFaces(self, faces: List[int]) -> None: ...

# =============================================================================
# Materials & Collections
# =============================================================================

class OMaterial:
    """Write material reference."""
    def __init__(self, name: str) -> None: ...
    def setTarget(self, target: str, shader_type: str) -> None: ...

class OCollections:
    """Write object collections."""
    def __init__(self) -> None: ...
    def addCollection(self, name: str, paths: List[str]) -> None: ...

class IMaterial:
    """Read material reference."""
    def getTargets(self) -> List[str]: ...
    def getShaderType(self, target: str) -> Optional[str]: ...

class ICollections:
    """Read object collections."""
    def getCollectionNames(self) -> List[str]: ...
    def getCollection(self, name: str) -> Optional[Collection]: ...

class Collection:
    """Collection data."""
    @property
    def name(self) -> str: ...
    @property
    def paths(self) -> List[str]: ...

# =============================================================================
# Properties
# =============================================================================

class ICompoundProperty:
    """Read compound property."""
    def getNumProperties(self) -> int: ...
    def getPropertyHeader(self, index: int) -> Optional[PropertyInfo]: ...
    def getProperty(self, name: str) -> Optional[ICompoundProperty]: ...

class PropertyInfo:
    """Property metadata."""
    @property
    def name(self) -> str: ...
    @property
    def propertyType(self) -> str: ...
    @property
    def dataType(self) -> str: ...
    @property
    def extent(self) -> int: ...

class OScalarProperty:
    """Write scalar property."""
    def __init__(self, name: str, data_type: str) -> None: ...
    def addSample(self, value: Any) -> None: ...

class OArrayProperty:
    """Write array property."""
    def __init__(self, name: str, data_type: str) -> None: ...
    def addSample(self, values: List[Any]) -> None: ...

class OCompoundProperty:
    """Write compound property."""
    def __init__(self, name: str) -> None: ...
    def addScalarProperty(self, prop: OScalarProperty) -> None: ...
    def addArrayProperty(self, prop: OArrayProperty) -> None: ...

# =============================================================================
# Visibility
# =============================================================================

class ObjectVisibility:
    """Visibility state."""
    Deferred: int
    Hidden: int
    Visible: int

class OVisibilityProperty:
    """Write visibility property."""
    def __init__(self) -> None: ...
    def addSample(self, visibility: int) -> None: ...

# =============================================================================
# Time Sampling
# =============================================================================

class TimeSampling:
    """Time sampling configuration."""
    @property
    def numSamples(self) -> int: ...
    def getSampleTime(self, index: int) -> float: ...
