"""Type stubs for alembic_rs Python bindings."""

from typing import List, Optional, Sequence, Tuple

# =============================================================================
# Archives
# =============================================================================

class IArchive:
    """Read-only Alembic archive."""
    
    def __init__(self, path: str) -> None: ...
    def getName(self) -> str: ...
    def getTop(self) -> IObject: ...
    def getNumTimeSamplings(self) -> int: ...
    def getTimeSampling(self, index: int) -> TimeSampling: ...
    def getMaxNumSamplesForTimeSamplingIndex(self, index: int) -> Optional[int]: ...
    def getArchiveVersion(self) -> int: ...
    def getArchiveVersionString(self) -> str: ...
    def valid(self) -> bool: ...
    def hasObject(self, path: str) -> bool: ...
    def getAppName(self) -> Optional[str]: ...
    def getDateWritten(self) -> Optional[str]: ...
    def getUserDescription(self) -> Optional[str]: ...
    def getDccFps(self) -> Optional[float]: ...
    def getMetadata(self, key: str) -> Optional[str]: ...
    def getMetadataKeys(self) -> List[str]: ...

class OArchive:
    """Write-only Alembic archive."""
    
    @staticmethod
    def create(path: str) -> OArchive: ...
    def getName(self) -> str: ...
    def setApplicationWriter(self, writer: str) -> None: ...
    def setCompressionHint(self, hint: int) -> None: ...
    def setDedupEnabled(self, enabled: bool) -> None: ...
    def setAppName(self, name: str) -> None: ...
    def setDateWritten(self, date: str) -> None: ...
    def setDescription(self, desc: str) -> None: ...
    def setDccFps(self, fps: float) -> None: ...
    def addUniformTimeSampling(self, fps: float, start_time: float = 0.0) -> int: ...
    def addAcyclicTimeSampling(self, times: List[float]) -> int: ...
    def addCyclicTimeSampling(self, time_per_cycle: float, times: List[float]) -> int: ...
    def writeArchive(self, root: OObject) -> None: ...
    def writePolyMesh(self, mesh: OPolyMesh) -> None: ...
    def writeXform(self, xform: OXform) -> None: ...

# =============================================================================
# Objects
# =============================================================================

class IObject:
    """Read-only object in the hierarchy."""
    
    def getName(self) -> str: ...
    def getFullName(self) -> str: ...
    def getNumChildren(self) -> int: ...
    def getChild(self, index: int) -> IObject: ...
    def getChildByName(self, name: str) -> Optional[IObject]: ...
    def hasChild(self, name: str) -> bool: ...
    def getParent(self) -> Optional[IObject]: ...
    def getTimeSamplingIndex(self) -> int: ...
    def getVisibility(self, sample_index: int) -> int: ...
    def isVisible(self, sample_index: int) -> bool: ...
    def isHidden(self, sample_index: int) -> bool: ...
    def getSelfBounds(self, sample_index: int) -> Optional[List[float]]: ...
    def getChildBounds(self, sample_index: int) -> Optional[List[float]]: ...
    def hasSelfBounds(self) -> bool: ...
    def hasChildBounds(self) -> bool: ...

class OObject:
    """Write-only object."""
    
    def __init__(self, name: str) -> None: ...
    def addChild(self, child: OObject) -> None: ...
    def addScalarProperty(self, name: str, data_type: str) -> OScalarProperty: ...
    def addArrayProperty(self, name: str, data_type: str) -> OArrayProperty: ...
    def addCompoundProperty(self, name: str) -> OCompoundProperty: ...
    def addVisibilityProperty(self) -> OVisibilityProperty: ...

# =============================================================================
# Time Sampling
# =============================================================================

class TimeSampling:
    """Time sampling information."""
    
    def isUniform(self) -> bool: ...
    def isCyclic(self) -> bool: ...
    def isAcyclic(self) -> bool: ...
    def getNumStoredTimes(self) -> int: ...
    def getStoredTimes(self) -> List[float]: ...
    def getTimePerCycle(self) -> float: ...
    def getSampleTime(self, index: int, num_samples: int) -> float: ...

# =============================================================================
# Geometry Types
# =============================================================================

class IPolyMesh:
    """Read-only PolyMesh schema."""
    
    def __init__(self, obj: IObject) -> None: ...
    def getNumSamples(self) -> int: ...
    def getSample(self, index: int) -> IPolyMeshSample: ...

class IPolyMeshSample:
    """PolyMesh sample data."""
    
    def getPositions(self) -> List[float]: ...
    def getFaceCounts(self) -> List[int]: ...
    def getFaceIndices(self) -> List[int]: ...
    def getNormals(self) -> Optional[List[float]]: ...
    def getUVs(self) -> Optional[List[float]]: ...

class OPolyMesh:
    """Write-only PolyMesh."""
    
    def __init__(self, name: str) -> None: ...
    def addSample(self, sample: OPolyMeshSample) -> None: ...
    def setTimeSamplingIndex(self, index: int) -> None: ...
    def build(self) -> OObject: ...

class OPolyMeshSample:
    """PolyMesh sample for writing."""
    
    def __init__(self) -> None: ...
    def setPositions(self, positions: Sequence[float]) -> None: ...
    def setFaceCounts(self, counts: Sequence[int]) -> None: ...
    def setFaceIndices(self, indices: Sequence[int]) -> None: ...
    def setNormals(self, normals: Sequence[float]) -> None: ...
    def setUVs(self, uvs: Sequence[float]) -> None: ...
    def setVelocities(self, velocities: Sequence[float]) -> None: ...

class IXform:
    """Read-only Xform schema."""
    
    def __init__(self, obj: IObject) -> None: ...
    def getNumSamples(self) -> int: ...
    def getSample(self, index: int) -> IXformSample: ...

class IXformSample:
    """Xform sample data."""
    
    def getMatrix(self) -> List[float]: ...
    def getTranslation(self) -> Tuple[float, float, float]: ...
    def getScale(self) -> Tuple[float, float, float]: ...
    def getRotation(self) -> Tuple[float, float, float]: ...
    def getRotationQuaternion(self) -> Tuple[float, float, float, float]: ...
    def isIdentity(self) -> bool: ...

class OXform:
    """Write-only Xform."""
    
    def __init__(self, name: str) -> None: ...
    def addSample(self, sample: OXformSample) -> None: ...
    def setTimeSamplingIndex(self, index: int) -> None: ...
    def build(self) -> OObject: ...

class OXformSample:
    """Xform sample for writing."""
    
    def __init__(self) -> None: ...
    def setTranslation(self, x: float, y: float, z: float) -> None: ...
    def setScale(self, x: float, y: float, z: float) -> None: ...
    def setRotationFromEuler(self, x: float, y: float, z: float) -> None: ...
    def setRotationFromQuaternion(self, x: float, y: float, z: float, w: float) -> None: ...
    def setMatrix(self, matrix: Sequence[float]) -> None: ...

class OCurves:
    """Write-only Curves."""
    
    def __init__(self, name: str) -> None: ...
    def addSample(self, sample: OCurvesSample) -> None: ...
    def setTimeSamplingIndex(self, index: int) -> None: ...
    def build(self) -> OObject: ...

class OCurvesSample:
    """Curves sample for writing."""
    
    def __init__(self) -> None: ...
    def setPositions(self, positions: Sequence[float]) -> None: ...
    def setNumVerts(self, num_verts: Sequence[int]) -> None: ...

class OPoints:
    """Write-only Points."""
    
    def __init__(self, name: str) -> None: ...
    def addSample(self, sample: OPointsSample) -> None: ...
    def setTimeSamplingIndex(self, index: int) -> None: ...
    def build(self) -> OObject: ...

class OPointsSample:
    """Points sample for writing."""
    
    def __init__(self) -> None: ...
    def setPositions(self, positions: Sequence[float]) -> None: ...
    def setIds(self, ids: Sequence[int]) -> None: ...

# =============================================================================
# Properties
# =============================================================================

class OScalarProperty:
    """Write-only scalar property."""
    
    def setTimeSamplingIndex(self, index: int) -> None: ...
    def addSampleInt(self, value: int) -> None: ...
    def addSampleFloat(self, value: float) -> None: ...
    def addSampleDouble(self, value: float) -> None: ...
    def addSampleBool(self, value: bool) -> None: ...
    def addSampleString(self, value: str) -> None: ...
    def addSampleVec2f(self, x: float, y: float) -> None: ...
    def addSampleVec3f(self, x: float, y: float, z: float) -> None: ...
    def addSampleVec4f(self, x: float, y: float, z: float, w: float) -> None: ...
    def addSampleVec3d(self, x: float, y: float, z: float) -> None: ...
    def addSampleMat44f(self, values: Sequence[float]) -> None: ...

class OArrayProperty:
    """Write-only array property."""
    
    def setTimeSamplingIndex(self, index: int) -> None: ...
    def addSampleInts(self, values: Sequence[int]) -> None: ...
    def addSampleUints(self, values: Sequence[int]) -> None: ...
    def addSampleFloats(self, values: Sequence[float]) -> None: ...
    def addSampleDoubles(self, values: Sequence[float]) -> None: ...
    def addSampleStrings(self, values: Sequence[str]) -> None: ...
    def addSampleVec2fs(self, values: Sequence[float]) -> None: ...
    def addSampleVec3fs(self, values: Sequence[float]) -> None: ...
    def addSampleVec4fs(self, values: Sequence[float]) -> None: ...

class OCompoundProperty:
    """Write-only compound property."""
    
    def addScalar(self, name: str, data_type: str) -> OScalarProperty: ...
    def addArray(self, name: str, data_type: str) -> OArrayProperty: ...
    def addCompound(self, name: str) -> OCompoundProperty: ...

# =============================================================================
# Visibility
# =============================================================================

class ObjectVisibility:
    """Object visibility values."""
    
    @staticmethod
    def deferred() -> int: ...
    @staticmethod
    def hidden() -> int: ...
    @staticmethod
    def visible() -> int: ...
    @staticmethod
    def fromValue(value: int) -> int: ...

class OVisibilityProperty:
    """Write-only visibility property."""
    
    def setVisible(self) -> None: ...
    def setHidden(self) -> None: ...
    def setDeferred(self) -> None: ...
    def set(self, value: int) -> None: ...
